import Link from 'next/link';
import { ArrowRight, ArrowUpRight, GitCompareArrows, Search, ShoppingBag } from 'lucide-react';

export const metadata = { title: 'Get to know NexMart' };
export default function AboutPage() {
  return <main id="main-content" className="store-page"><div className="page-container">
    <header className="grid items-end gap-8 border-b border-white/15 pb-10 lg:grid-cols-[1.3fr_1fr]"><div><p className="eyebrow mb-5 text-violet-200">Get to know NexMart</p><h1 className="text-4xl font-medium leading-[1.08] sm:text-6xl">More clarity.<br />Better everyday choices.</h1></div><div><p className="text-base leading-relaxed text-secondary">NexMart brings product discovery, useful details, and your shopping journey together. Our aim is to make the next choice a little easier to understand.</p><Link href="/categories" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm text-violet-200">Find your direction <ArrowUpRight size={17} aria-hidden /></Link></div></header>
    <section className="grid gap-7 py-10 md:grid-cols-3" aria-label="The shopping experience">{[{ Icon: Search, number: '01', title: 'Follow your curiosity.', copy: 'Start with a department, search by a product detail, or refine the collection by brand, price, and availability.' }, { Icon: GitCompareArrows, number: '02', title: 'Look a little closer.', copy: 'Explore imagery, compare options and specifications, and see the selected price before adding anything to your cart.' }, { Icon: ShoppingBag, number: '03', title: 'Keep it in view.', copy: 'Review the total before ordering. Your account keeps saved products, addresses, payment status, and delivery updates together.' }].map(({ Icon, number, title, copy }) => <div key={number} className="rounded-xl border border-white/15 bg-space-800 p-6"><div className="mb-9 flex items-center justify-between"><Icon size={26} className="text-violet-200" aria-hidden /><span className="font-mono text-xs text-muted">{number} /</span></div><h2 className="text-2xl">{title}</h2><p className="mt-4 text-sm leading-relaxed text-secondary">{copy}</p></div>)}</section>
    <section className="grid gap-6 rounded-2xl border border-white/15 p-6 sm:p-9 lg:grid-cols-2"><div><p className="eyebrow mb-3">A catalog taking shape</p><h2 className="section-heading">A clear distinction<br />between inspiration and inventory.</h2></div><div><p className="text-sm leading-relaxed text-secondary">The collection includes clearly marked sample products while the store is being developed. Samples use illustrative prices, carry no invented reviews, and cannot be purchased. Actual stock is distinguished with the availability filter.</p><p className="mt-4 text-sm leading-relaxed text-secondary">Business contacts and commercial policies are still awaiting operator confirmation. The policy pages make that publication status visible, so you don’t have to guess.</p><div className="mt-4 flex flex-wrap gap-x-6"><Link href="/products?inStock=true" className="inline-flex min-h-11 items-center gap-2 text-sm text-violet-200">Available to buy <ArrowUpRight size={15} aria-hidden /></Link><Link href="/contact" className="inline-flex min-h-11 items-center gap-2 text-sm text-secondary">Business information <ArrowUpRight size={15} aria-hidden /></Link></div></div></section>
    <section className="flex flex-wrap items-center justify-between gap-5 py-10"><div><h2 className="section-heading">Your next find starts here.</h2><p className="mt-3 text-sm text-muted">Explore the everyday edit, or head straight for what you need.</p></div><Link href="/products" className="btn-primary">Explore the collection <ArrowRight size={17} aria-hidden /></Link></section>
  </div></main>;
}
