'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Package, Plus, Search } from 'lucide-react';
import { policyLinks } from '@/lib/businessDetails';

const questions = [
  { group: 'Finding products', title: 'How do search and filters work together?', answer: 'Search a product type, model, brand, or useful detail such as storage. Selected brands and categories are combined within their own group; price, availability, and other filters narrow those results together. Remove a filter chip to broaden the collection.' },
  { group: 'Finding products', title: 'Why do some results say “close matches”?', answer: 'If no exact matches are found, the catalog can show products matching a nearby spelling. This is stated above the results, and your selected filters still apply.' },
  { group: 'Finding products', title: 'What does the Sample label mean?', answer: 'Sample items let you explore category layouts, images, specifications, options, and comparison. Their prices are illustrative, and they cannot be purchased. Use “Available to buy” to see non-sample inventory that is currently in stock.' },
  { group: 'Finding products', title: 'Can I compare products or take a quick look?', answer: 'Choose Compare on up to three product cards, then open the comparison tray for a side-by-side view. Quick look shows images, options, and important details without losing your place in the collection.' },
  { group: 'Cart & payments', title: 'Why did a product price change after I chose an option?', answer: 'Different product options or seller offers can have different prices. A filtered card links to the option whose price it displayed. Always check the selected option and seller in your cart; a changed price is flagged before you continue.' },
  { group: 'Cart & payments', title: 'How is my total calculated?', answer: 'The cart lists current item prices (all inclusive of GST), shipping, the GST amount already included in the price, and the total. Review the final amount and delivery address before ordering. Commercial shipping terms and category-specific tax treatment still need operator confirmation; consult the draft Shipping page for the current publication status.' },
  { group: 'Cart & payments', title: 'How can I pay?', answer: 'The checkout offers online payment through Razorpay and cash on delivery where enabled. The payment provider shows the online methods available for your transaction. Never share a banking PIN, password, or sign-in code with a seller.' },
  { group: 'Cart & payments', title: 'What if an online payment is interrupted?', answer: 'Check your order’s payment status before retrying. If your bank reports a debit, avoid paying again until the first transaction is resolved. Order creation, successful payment, and a refund are different statuses.' },
  { group: 'Orders & delivery', title: 'Where can I track an order?', answer: 'Sign in, open Orders, and select the order. Its recorded payment status and delivery progress are shown separately. Marketplace orders may include separate seller fulfillment groups and shipments.', href: '/orders', link: 'Open your orders' },
  { group: 'Orders & delivery', title: 'Does “in stock” promise a delivery date?', answer: 'No. In-stock status describes current inventory. A seller handling time is an estimate for preparation or dispatch, not an arrival guarantee. Delivery coverage and timelines need to be stated by the operator.', href: '/shipping', link: 'Read delivery information' },
  { group: 'Returns & support', title: 'Can I return or cancel an order?', answer: 'Review any seller-specific terms and the Returns page before ordering. A universal return window and a customer self-service cancellation process have not yet been published. Statutory remedies for defective or misdescribed goods are not removed by a lack of voluntary returns.', href: '/returns', link: 'Read returns & cancellations' },
  { group: 'Returns & support', title: 'How can I contact customer care?', answer: 'The Contact page shows which business and support details have been published. The operator still needs to confirm functioning customer-care and grievance channels. There is no active support form here, so do not assume a request has been submitted.', href: '/contact', link: 'View contact status' },
  { group: 'Your account', title: 'Do I need an account to browse?', answer: 'You can browse, search, compare, and build a guest cart without an account. Sign in to save products to your wishlist, place an order, and view your account history.' },
  { group: 'Your account', title: 'Where are my saved addresses and security settings?', answer: 'Your profile contains supported personal information, saved addresses, and account security controls. You can manage passwords and active sign-in access there.', href: '/profile', link: 'Open your profile' },
];

export function HelpCenter() {
  const [search, setSearch] = useState('');
  const [group, setGroup] = useState('All topics');
  const groups = ['All topics', ...new Set(questions.map(question => question.group))];
  const visible = questions.filter(question => (group === 'All topics' || question.group === group) && `${question.title} ${question.answer}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
  return <main id="main-content" className="store-page"><div className="page-container">
    <header className="mb-8 rounded-2xl border border-white/15 bg-space-800 p-6 sm:p-9"><p className="eyebrow mb-3 text-violet-200">A little guidance goes a long way</p><h1 className="text-4xl font-medium sm:text-5xl">How can we help?</h1><p className="mt-4 text-sm text-secondary">Find your way around the catalog, your cart, and everything after checkout.</p><label htmlFor="help-search" className="sr-only">Search shopping help</label><div className="relative mt-6 max-w-xl"><Search size={18} className="absolute left-4 top-3.5 text-muted" aria-hidden /><input id="help-search" value={search} type="search" onChange={event => setSearch(event.target.value)} className="input pl-11" placeholder="Search a question, such as payment or returns" /></div></header>
    <div className="grid gap-8 lg:grid-cols-[230px_minmax(0,1fr)_280px]"><nav aria-label="Help topics" className="flex flex-wrap content-start gap-2 lg:flex-col">{groups.map(topic => <button key={topic} type="button" aria-pressed={topic === group} onClick={() => setGroup(topic)} className={`min-h-11 rounded-lg border px-3 py-2 text-left text-sm ${topic === group ? 'border-violet-300/50 bg-violet-500/10 text-white' : 'border-white/15 text-secondary hover:bg-white/5'}`}>{topic}</button>)}</nav>
      <section aria-label="Frequently asked questions"><p role="status" className="mb-2 text-xs text-muted">{visible.length} {visible.length === 1 ? 'answer' : 'answers'}</p>{visible.length ? visible.map(question => <details key={question.title} className="faq-item"><summary>{question.title}<Plus size={18} className="shrink-0 text-muted" aria-hidden /></summary><p className="mt-4 text-sm leading-relaxed text-secondary">{question.answer}</p>{question.href && <Link href={question.href} className="mt-2 inline-flex min-h-11 items-center gap-1.5 text-sm text-violet-200">{question.link}<ArrowUpRight size={14} aria-hidden /></Link>}</details>) : <div className="rounded-xl border border-white/15 p-6"><h2 className="text-xl">No answers match just yet.</h2><p className="mt-2 text-sm text-secondary">Try a broader word or explore all topics.</p><button type="button" className="btn-secondary mt-4" onClick={() => { setSearch(''); setGroup('All topics'); }}>Show all questions</button></div>}</section>
      <aside className="space-y-5"><div className="rounded-xl border border-white/15 bg-space-800 p-5"><Package size={24} className="mb-4 text-violet-200" aria-hidden /><h2 className="text-xl">Looking for your order?</h2><p className="mt-3 text-sm text-muted">Check the latest recorded payment and delivery updates.</p><Link href="/orders" className="btn-secondary mt-5 w-full">View your orders</Link></div><nav aria-label="Shopping information" className="rounded-xl border border-white/15 p-5"><h2 className="mb-3 text-lg">Good to know</h2>{policyLinks.map(link => <Link key={link.href} href={link.href} className="flex min-h-11 items-center justify-between gap-2 text-sm text-secondary">{link.label}<ArrowUpRight size={14} aria-hidden /></Link>)}</nav></aside>
    </div>
  </div></main>;
}
