export interface PolicySection { id: string; title: string; paragraphs: string[]; points?: string[] }
export interface StorefrontPolicy { title: string; description: string; summary: string[]; sections: PolicySection[] }

export const storefrontPolicies: Record<'terms' | 'privacy' | 'shipping' | 'returns', StorefrontPolicy> = {
  terms: {
    title: 'Terms & conditions',
    description: 'A clear starting point for browsing, choosing, and ordering on NexMart.',
    summary: ['Check the selected product option and seller before ordering.', 'Sample products are for catalog exploration, not purchase.', 'Your statutory consumer rights are not waived by these pages.'],
    sections: [
      { id: 'operator', title: '01. Who operates the store', paragraphs: ['NexMart is the storefront brand. The operator’s legal name, registered address, customer-care contacts, and grievance officer must be confirmed and published on the Contact page before these terms become final. A brand name alone does not identify the contracting business.', 'This draft explains the current shopping experience. It is not a substitute for approved commercial terms or a final contract.'] },
      { id: 'account', title: '02. Your account', paragraphs: ['Use accurate contact and delivery details, keep your sign-in credentials private, and use only payment methods you are authorised to use. You are responsible for checking your delivery address and selected product options before submission.', 'Account eligibility, contracting capacity, and the process for closing an account require operator approval in the final terms. Do not submit another person’s private information without a lawful basis.'] },
      { id: 'catalog', title: '03. Products, options, and sample items', paragraphs: ['Product pages show the information supplied for a listing. Specifications, colour, size, condition, price, stock, and the selected seller may differ between options. Images are illustrative; rely on the stated specifications and ask for clarification where details are missing.', 'Items marked “Sample” are demonstration catalog entries. Their INR prices are illustrative, they have no saleable inventory, and they cannot be ordered. They do not imply an authorised brand partnership, warranty, customer review, or available stock.'] },
      { id: 'orders', title: '04. Prices, payments, and order status', paragraphs: ['Review item prices, tax, shipping, and the final total in your cart and checkout. Online payments use Razorpay; available methods are shown by the payment provider. Cash on delivery appears where enabled by the store.', 'Order creation, payment confirmation, and fulfillment are separate events. An order awaiting payment is not evidence of a successful payment. If a payment is interrupted, check the order and bank status before retrying.', 'The operator must confirm when an order becomes contractually accepted, how pricing or availability errors are handled, the applicable tax treatment, and how any refund is communicated. This draft does not reserve an unrestricted right to cancel paid orders.'] },
      { id: 'sellers', title: '05. Marketplace offers', paragraphs: ['Where multiple seller offers exist, inspect the seller, selected option, condition, price, handling time, return window, and warranty information before adding an offer to the cart. A seller’s handling time describes dispatch, not a guaranteed delivery date.', 'Responsibility for fulfillment, invoices, warranties, and disputes must be stated in the final marketplace terms. No marketplace disclaimer overrides rights that apply under consumer law.'] },
      { id: 'conduct', title: '06. Fair use and reviews', paragraphs: ['Do not misuse accounts, interfere with the service, attempt unauthorised access, submit unlawful material, or create misleading reviews. Reviews should describe a genuine experience and must not disclose personal information.', 'A verified-purchase label is tied to a recorded delivered purchase. Unverified feedback is not represented as a verified purchase. Products are not given invented customer ratings.'] },
      { id: 'rights', title: '07. Shipping, returns, and your rights', paragraphs: ['Read the Shipping and Returns pages alongside the product and seller details. Delivery coverage, cancellation rules, return eligibility, warranty arrangements, and refund timelines require operator confirmation. Do not assume a universal delivery deadline or return window.', 'Nothing on these pages excludes non-waivable rights for defective, misdescribed, or otherwise non-conforming goods. The final terms must be reviewed for the applicable Indian consumer and e-commerce requirements.'] },
      { id: 'changes', title: '08. Questions and future changes', paragraphs: ['Use the Contact page for the publication status of support and grievance channels. Once final terms are approved, material revisions should be dated and made accessible; changes should not silently rewrite the terms of an existing order.'] },
    ],
  },
  privacy: {
    title: 'Privacy notice',
    description: 'What information the shopping experience uses, and what still needs to be confirmed.',
    summary: ['Account, delivery, and order data support the shopping flow.', 'Payments are handled through Razorpay, not a store card-entry form.', 'Browser storage keeps your cart, account state, and recent searches.'],
    sections: [
      { id: 'responsibility', title: '01. Who is responsible', paragraphs: ['The legal identity and privacy contact of the NexMart operator have not yet been published. They must be added to the Contact page before this notice is final. This draft describes the implemented features; it is not a declaration of regulatory compliance.'] },
      { id: 'information', title: '02. Information used by the service', paragraphs: ['Depending on which features you use, the service processes the following information:'], points: ['Account name, email address, authentication-provider information, verification status, and password hashes for password-based accounts.', 'Delivery addresses, recipient names, phone numbers, saved address preferences, and order details.', 'Cart items, saved products, submitted reviews, payment references and statuses, delivery events, and invoices where available.', 'Technical request information used for operation, security, rate limiting, and troubleshooting. The final notice must enumerate deployed logging and retention settings.'] },
      { id: 'purposes', title: '03. Why it is used', paragraphs: ['These features use information to create and authenticate accounts, maintain carts and orders, process payments, coordinate delivery, display order progress, send service communications, prevent abuse, and investigate failures.', 'Additional uses, marketing, or non-essential tracking require their own documented purpose and appropriate choice or consent. This draft is not permission to add new processing silently.'] },
      { id: 'providers', title: '04. Service providers and sharing', paragraphs: ['The implementation uses MongoDB for stored application data, Redis services for security and caching, Cloudinary for media and generated files, and Razorpay for online payments. Email, delivery, hosting, and any configured sign-in providers may also process information needed to perform their function.', 'The store does not ask you to enter raw card details into its own form. Online payment entry happens in the payment provider’s interface. Transaction identifiers and payment status may be retained by the store.', 'Public catalog images may be loaded from Cloudinary, DummyJSON, or Open Library. Image hosting or optimisation may involve requests to those providers. The operator must verify active providers, contracts, hosting regions, transfers, and access controls before final publication.'] },
      { id: 'storage', title: '05. Cookies and browser storage', paragraphs: ['Authentication uses session cookies. Browser storage also keeps cart/session identifiers, a cached account summary, and recent search terms. This helps the site remember shopping state between visits.', 'Recent searches can be cleared from the search panel. Signing out ends the normal sign-in flow; the account security screen also offers controls such as signing out everywhere. Clearing site data in your browser can remove locally saved information but may interrupt sign-in and cart continuity.', 'A current cookie/storage inventory, exact lifetimes, and any non-essential consent mechanism must be verified against the deployed site.'] },
      { id: 'retention', title: '06. Retention and security', paragraphs: ['Passwords are stored as hashes, not as readable passwords. Access controls and session checks restrict account features, but no system can promise absolute security.', 'The operator has not yet approved a retention schedule. Order, tax, fraud-prevention, and dispute records may need to be retained where law requires; this does not justify indefinite retention of every data type. Retention periods and deletion procedures must be documented before this notice is final.'] },
      { id: 'choices', title: '07. Your choices and requests', paragraphs: ['You can update supported profile and address fields, manage saved products, clear recent searches, and use account security controls. A verified contact channel and a working request process are still required for access, correction, deletion, consent withdrawal where applicable, and grievances.', 'Do not send passwords, verification codes, complete card numbers, or sensitive documents through public reviews. The final notice must identify how requests are verified and handled, including any lawful retention exceptions.'] },
      { id: 'children', title: '08. Children and legal review', paragraphs: ['The operator must define and implement age-appropriate account eligibility, protections for children’s data where applicable, and any necessary parental-consent process. This draft does not assert that those controls already exist.', 'Indian privacy requirements have staged commencement dates. The operator should review the law in force at launch, including the Digital Personal Data Protection framework, and align actual processing with the final notice.'] },
    ],
  },
  shipping: {
    title: 'Shipping & delivery',
    description: 'Know what happens between checkout and your doorstep.',
    summary: ['Check your complete delivery address before ordering.', 'Seller handling time is not a guaranteed arrival date.', 'Follow payment and delivery status separately in Orders.'],
    sections: [
      { id: 'coverage', title: '01. Delivery coverage', paragraphs: ['The operator has not yet published supported pincodes, delivery exclusions, or serviceability commitments. A valid address format does not, by itself, confirm that a courier can serve that address.', 'Confirm delivery availability through the published support channel before placing an order if coverage is unclear. Sample catalog products are not dispatched.'] },
      { id: 'charges', title: '02. Shipping charges and the total', paragraphs: ['Your cart and checkout display the shipping charge used for the current order calculation, alongside item prices and tax. Review the total before payment.', 'A universal free-shipping threshold, remote-area surcharge, and multi-seller shipping policy have not been commercially approved for publication. The operator must ensure the checkout calculation matches the final policy and applicable tax rules.'] },
      { id: 'timing', title: '03. Processing and delivery estimates', paragraphs: ['A seller offer may display a handling time. This describes the seller’s stated time to prepare or dispatch an item, not the transit time or a guaranteed delivery date.', 'No store-wide dispatch deadline, transit-time range, cut-off time, holiday schedule, or guaranteed delivery service is published yet. Do not infer same-day or next-day delivery from product availability. The operator must provide accurate estimates before a customer commits to an order.'] },
      { id: 'tracking', title: '04. Tracking your order', paragraphs: ['Sign in, open Orders, and select an order to view its recorded status. Payment status and order/fulfillment status are separate. A paid order can still be awaiting dispatch.', 'Marketplace orders may have separate fulfillment groups or shipments. Where tracking details exist, the order view shows the available updates; the absence of an update is not proof of delivery.'] },
      { id: 'address', title: '05. Addresses and delivery issues', paragraphs: ['Provide the recipient’s correct name, reachable phone number, address, city, state, and pincode. Check these before submission. Do not assume an address can be changed after dispatch.', 'For an incorrect address, delay, damaged parcel, missing item, or a “delivered” status you do not recognise, keep your order reference and use the published support channel. Do not expose your address or phone number in a product review.', 'The operator must confirm the process for failed attempts, refusal, re-delivery, address corrections, and lost shipments, including any charges and consumer remedies.'] },
    ],
  },
  returns: {
    title: 'Returns & cancellations',
    description: 'Understand eligibility, refunds, and what to check before you order.',
    summary: ['There is no published universal return window yet.', 'Check seller-specific terms and the selected product condition.', 'Defective or misdescribed goods may carry statutory remedies.'],
    sections: [
      { id: 'eligibility', title: '01. Return eligibility', paragraphs: ['A store-wide return or exchange policy has not yet been approved. Where a seller offer shows a return window or warranty, read that information before ordering and ask for clarification if it is incomplete.', 'Change-of-mind returns may depend on product category, condition, seals, accessories, and seller terms. No category-specific exclusions are invented by this draft. Final rules must clearly cover areas such as food, personal-care items, electronics, apparel, and books.'] },
      { id: 'problems', title: '02. Incorrect, damaged, or defective goods', paragraphs: ['Keep the order reference and relevant photos or product details when reporting an incorrect, damaged, defective, incomplete, or misdescribed delivery. Preserve packaging where practical, but do not assume that packaging alone determines your statutory rights.', 'A listing with no voluntary return window does not automatically remove remedies required by law. The final process must explain inspection, replacement, repair where applicable, refund, and who pays return shipping.'] },
      { id: 'cancellation', title: '03. Cancellations', paragraphs: ['Check your order status before requesting cancellation. An order already dispatched may need a different process from one awaiting fulfillment. A cancellation request is not confirmation that cancellation has completed.', 'Customer self-service cancellation is not currently promised by this page. The operator must publish the request channel, cut-off rules, seller obligations, and any lawful charges before these terms become final.'] },
      { id: 'request', title: '04. How to raise an issue', paragraphs: ['Open the order in your account and keep its reference available. Use the contact and grievance details on the Contact page once they are published. Describe the problem and the remedy you are requesting.', 'Do not return a parcel to an assumed address. The correct return address, authorisation process, pickup/drop-off method, required documentation, and tracking steps must be supplied by the operator or responsible seller. Never share a password or one-time sign-in code to request a refund.'] },
      { id: 'refunds', title: '05. Refunds and interrupted payments', paragraphs: ['Check the recorded payment status and any refund updates in your order. If your bank shows a debit after an interrupted payment, avoid paying again until that transaction is resolved.', 'Refund approval, initiation, and arrival in the customer’s account are different stages. The operator must publish processing timelines and the refund method for online and cash-on-delivery orders. Bank or payment-network processing can add time after initiation; this draft does not promise a specific number of days.', 'Do not confuse an order cancellation with a completed refund. The amount, deductions if lawful, and transaction reference should be communicated when a refund is processed.'] },
      { id: 'grievances', title: '06. Escalation and consumer rights', paragraphs: ['The operator must publish a named grievance officer and a functioning contact channel. Applicable Indian e-commerce rules include responsibilities to acknowledge a consumer complaint within 48 hours and redress it within one month. These statutory responsibilities are distinct from commercial refund-processing timelines.', 'Nothing here limits access to applicable consumer remedies. You may also consult the National Consumer Helpline through its official website. Final policies should be reviewed against actual operations before the store is launched commercially.'] },
    ],
  },
};
